;(load "global_path.clp")
;(bind ?*path* (str-cat ?*path* "/src/clp_files/gen-neg_rstr-rstd.clp"))
;(load ?*path*)
;(load-facts "hin-clips-facts.dat")
;(load-facts "updated_mrs_feature_info.dat")
;;(load-facts "mrs_info_binding_features_values.dat")
;(open "mrs_info_neg_rstr-rstd.dat" open-rstr "w")
;(open "mrs_info_neg_rstr-rstd_debug.dat" debug_rstr "w")
;(run)
;(close open-rstr)
;(close debug_rstr)
;(clear)
;---------------------------------------------------------------
(load "global_path.clp")
(bind ?*path* (str-cat ?*path* "/src/clp_files/bind-RSTR_RSTD-values.clp"))
(load ?*path*)
(load-facts "hin-clips-facts.dat")
(load-facts "hin_concept-to-mrs_concept.dat")
(load-facts "updated_mrs_feature_info.dat")
(open "mrs_info_with_rstr_rstd_values.dat" open-rstr "w")
(open "mrs_info_with_rstr_rstd_values_debug.dat" debug_rstr "w")
(run)
(close open-rstr)
(close debug_rstr)
(clear)
;---------------------------------------------------------------
(load "global_path.clp")
(bind ?*path* (str-cat ?*path* "/src/clp_files/bind-tense-etc.clp"))
(load ?*path*)
(load-facts "hin-clips-facts.dat")
(load-facts "updated_mrs_feature_info.dat")
(open "bind-mrs-tense-etc.dat" open-tense "w")
(open "bind-mrs-tense-etc_debug.dat" debug_tense "w")
(run)
(close open-tense)
(close debug_tense)
(clear)
(exit)
