(load "global_path.clp")
(bind ?*path* (str-cat ?*path* "/src/clp_files/bind-RSTR_RSTD-values.clp"))
(load ?*path*)
(load-facts "LS-UC_facts.dat")
(load-facts "hin_concept-MRS_surface_predicate.dat")
(load-facts "updated_mrs_feature_info.dat")
(open "mrs_info_with_rstr_rstd_values.dat" open-rstr "w")
(open "mrs_info_with_rstr_rstd_values_debug.dat" debug_rstr "w")
(run)
(close open-rstr)
(close debug_rstr)
(clear)
;---------------------------------------------------------------
(load "global_path.clp")
(bind ?*path* (str-cat ?*path* "/src/clp_files/bind-tense.clp"))
(load ?*path*)
(load-facts "LS-UC_facts.dat")
(load-facts "updated_mrs_feature_info.dat")
(open "bound_MRS_tense.dat" open-tense "w")
(open "bound_MRS_tense_debug.dat" debug_tense "w")
(run)
(close open-tense)
(close debug_tense)
(clear)
(exit)
