import os
import subprocess
import sys

input_folder = sys.argv[1]  # Get the input_folder from command-line arguments
all_veri_usr_out = "hin_verified_out" # output will come in this file 
output_file = " "
first_line = " "
hin_gen_comm = "generate_input_modularize_new.py" # This is the command to generate hindi sentences from USRs
hin_gen_out = "morph_input.txt-out.txt" # This file contains the output of the generated by above command
usr_files = os.listdir(input_folder)

usr_files.sort()
for filename in usr_files:
    with open(input_folder+"/"+filename, "r") as firstline:
        first_line = firstline.readline()
        #print("zzzzz")

        subprocess.run(["python3", hin_gen_comm, input_folder+"/"+filename]) # Running the command for each USR file present in the input folder

        with open(hin_gen_out, "r") as hout:
            hindiout = hout.read()
            # print(filename, hindiout)
            output_file = output_file + "\n" + filename + "\n" + first_line + hindiout + "\n"
            # print(output_file)

            with open(all_veri_usr_out, "w") as outf:
                outf.write(output_file)
